Repository microcks/microcks-testcontainers-dotnet, pull requests merged in 2025-01, with the labels that each got.

#13 feat: Add KAFKA mocking
  .github/workflows/cicd.yml
  .github/workflows/steps.dotnet-build-test.yml
  .gitignore
  README.md
  microcks-testcontainers-dotnet.sln
  src/Microcks.Testcontainers/Connection/KafkaConnection.cs
  src/Microcks.Testcontainers/Microcks.Testcontainers.csproj
  src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs
  src/Microcks.Testcontainers/MicrocksAsyncMinionConfiguration.cs
  src/Microcks.Testcontainers/MicrocksAsyncMinionContainer.cs
  src/Microcks.Testcontainers/MicrocksBuilder.cs
  src/Microcks.Testcontainers/MicrocksContainer.cs
  src/Microcks.Testcontainers/MicrocksContainerEnsemble.cs
  src/Microcks.Testcontainers/MicrocksContainerExtensions.cs
  src/Microcks.Testcontainers/MicrocksException.cs
  src/Microcks.Testcontainers/Model/EventMessage.cs
  src/Microcks.Testcontainers/Model/UnidirectionalEvent.cs
  tests/Microcks.Testcontainers.Tests/Async/Kafka/KafkaCollection.cs
  tests/Microcks.Testcontainers.Tests/Async/Kafka/KafkaContainerHelper.cs
  tests/Microcks.Testcontainers.Tests/Async/Kafka/MicrocksAsyncKafkaFunctionalityTest.cs
  tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
  tests/Microcks.Testcontainers.Tests/Microcks.Testcontainers.Tests.csproj
  tests/Microcks.Testcontainers.Tests/MicrocksMockingFunctionalityTest.cs
  tests/Microcks.Testcontainers.Tests/MicrocksSecretCreationTests.cs
  tests/Microcks.Testcontainers.Tests/pastry-orders-asyncapi.yml
Labels: component/documentation, component/runtime, component/settings, kind/feature

#29 feat: Add WebSocket Protocol
  README.md
  src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs
  src/Microcks.Testcontainers/MicrocksAsyncMinionContainer.cs
  src/Microcks.Testcontainers/MicrocksContainer.cs
  src/Microcks.Testcontainers/MicrocksContainerEnsemble.cs
  tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
Labels: component/documentation, component/runtime, component/settings, kind/feature

#33 refactor: remove Fluent Assertions from unit tests
  tests/Microcks.Testcontainers.Tests/Async/Kafka/MicrocksAsyncKafkaFunctionalityTest.cs
  tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
  tests/Microcks.Testcontainers.Tests/Microcks.Testcontainers.Tests.csproj
  tests/Microcks.Testcontainers.Tests/MicrocksContractTestingFunctionalityTests.cs
  tests/Microcks.Testcontainers.Tests/MicrocksMockingFunctionalityTest.cs
  tests/Microcks.Testcontainers.Tests/MicrocksSecretCreationTests.cs
Labels: dependencies, kind/task

#39 fix: Update steps.dotnet-build-test.yml #38
  .github/workflows/steps.dotnet-build-test.yml
Labels: kind/task

#41 Add contract testing for OIDC/OAuth2 protected resources
  src/Microcks.Testcontainers/Model/OAuth2AuthorizedClient.cs
  src/Microcks.Testcontainers/Model/OAuth2ClientContext.cs
  src/Microcks.Testcontainers/Model/OAuth2GrantType.cs
  src/Microcks.Testcontainers/Model/TestResult.cs
  tests/Microcks.Testcontainers.Tests/Microcks.Testcontainers.Tests.csproj
  tests/Microcks.Testcontainers.Tests/MicrocksContractTestingFunctionalityWithOAuth2Tests.cs
  tests/Microcks.Testcontainers.Tests/myrealm-realm.json
Labels: component/documentation, kind/enhancement, component/runtime
