Repository microcks/microcks-testcontainers-dotnet, pull requests merged in 2025-05, with the labels that each got.

#70 feat: #24 Allow verifying invocation and get invocation count
  README.md
  src/Microcks.Testcontainers/Microcks.Testcontainers.csproj
  src/Microcks.Testcontainers/MicrocksContainerExtensions.cs
  src/Microcks.Testcontainers/Model/DailyInvocationStatistic.cs
  tests/Microcks.Testcontainers.Tests/MicrocksContractTestingFunctionalityTests.cs
  tests/Microcks.Testcontainers.Tests/MicrocksMockingFunctionalityTest.cs
Labels: component/documentation, kind/enhancement, component/settings

#72 fix: flaky tests on WebSocket Tests
  tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
  tests/Microcks.Testcontainers.Tests/Async/WaitForConditionAsyncTests.cs
  tests/Microcks.Testcontainers.Tests/Async/WsCollection.cs
Labels: kind/bug, .NET

#75 chore(test): migrate from xunit v2 to xunit.v3
  tests/Microcks.Testcontainers.Tests/Async/Amqp/MicrocksAsyncAmqpFeatureTest.cs
  tests/Microcks.Testcontainers.Tests/Async/Kafka/MicrocksAsyncKafkaFunctionalityTest.cs
  tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureFixture.cs
  tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
  tests/Microcks.Testcontainers.Tests/Async/WaitForConditionAsyncTests.cs
  tests/Microcks.Testcontainers.Tests/Async/WsCollection.cs
  tests/Microcks.Testcontainers.Tests/Microcks.Testcontainers.Tests.csproj
  tests/Microcks.Testcontainers.Tests/MicrocksContractTestingFunctionalityTests.cs
  tests/Microcks.Testcontainers.Tests/MicrocksContractTestingFunctionalityWithOAuth2Tests.cs
  tests/Microcks.Testcontainers.Tests/MicrocksMockingFunctionalityTest.cs
  tests/Microcks.Testcontainers.Tests/MicrocksSecretCreationTests.cs
Labels: dependencies, kind/task, keep-open
